USE waybill_admin;

ALTER TABLE vehicle
  MODIFY COLUMN truck_type ENUM('4.2M', '6.8M', '9.6M', '17.5M') NOT NULL;

ALTER TABLE pricing_rule
  MODIFY COLUMN truck_type ENUM('4.2M', '6.8M', '9.6M', '17.5M') NOT NULL;

ALTER TABLE waybill_202607_0
  MODIFY COLUMN status ENUM('DRAFT', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'SIGNED', 'POD_UPLOADED') NOT NULL;

ALTER TABLE waybill_202607_1
  MODIFY COLUMN status ENUM('DRAFT', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'SIGNED', 'POD_UPLOADED') NOT NULL;

ALTER TABLE waybill_202607_2
  MODIFY COLUMN status ENUM('DRAFT', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'SIGNED', 'POD_UPLOADED') NOT NULL;

ALTER TABLE waybill_202607_3
  MODIFY COLUMN status ENUM('DRAFT', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'SIGNED', 'POD_UPLOADED') NOT NULL;

ALTER TABLE waybill_fee_detail
  MODIFY COLUMN fee_type ENUM('LINE_HAUL', 'LOADING', 'INSURANCE', 'SUBSIDY', 'DEDUCTION') NOT NULL;

ALTER TABLE waybill_operation_log
  MODIFY COLUMN operation_type ENUM('CREATE', 'SIGN', 'UPLOAD_POD') NOT NULL;

ALTER TABLE inbox_event
  MODIFY COLUMN event_type ENUM('WAYBILL_STATUS_CHANGED') NOT NULL,
  MODIFY COLUMN consume_status ENUM('NEW', 'RETRYING', 'CONSUMED', 'FAILED', 'DEAD_LETTER') NOT NULL DEFAULT 'NEW';

ALTER TABLE outbox_event
  MODIFY COLUMN event_type ENUM('WAYBILL_STATUS_CHANGED') NOT NULL,
  MODIFY COLUMN publish_status ENUM('NEW', 'PUBLISHED', 'FAILED', 'DEAD_LETTER') NOT NULL DEFAULT 'NEW';
